spring:
  kafka:
    bootstrap-server: "localhost:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.LongSerializer"
      value-serializer: "ru.practicum.avro.serialization.AvroSerializer"

topic:
  user-actions: "stats.user-actions.v1"

grpc:
  server:
    port: 0